export interface SampleEmployeeRow {
  "Employee Name": string;
  "Mobile Number": string;
  "City": string;
  "Full Address": string;
  "Email": string;
  "Salary Type": "Monthly" | "Daily";
  "Salary Amount (INR)": number;
  "Emergency Contact Name": string;
  "Emergency Contact Relation": string;
  "Emergency Contact Number": string;
}

export const SAMPLE_50_EMPLOYEES: SampleEmployeeRow[] = [
  {
    "Employee Name": "Aarav Sharma",
    "Mobile Number": "9876540001",
    "City": "Hyderabad",
    "Full Address": "Plot 12, Road No 3, Banjara Hills, Hyderabad 500034",
    "Email": "aarav.sharma@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 28000,
    "Emergency Contact Name": "Pooja Sharma",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541001",
  },
  {
    "Employee Name": "Ananya Reddy",
    "Mobile Number": "9876540002",
    "City": "Hyderabad",
    "Full Address": "Flat 302, Sri Sai Towers, Madhapur, Hyderabad 500081",
    "Email": "ananya.reddy@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 24000,
    "Emergency Contact Name": "Venkat Reddy",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541002",
  },
  {
    "Employee Name": "Bhavesh Patel",
    "Mobile Number": "9876540003",
    "City": "Ahmedabad",
    "Full Address": "45, Shivalik Residency, Satellite, Ahmedabad 380015",
    "Email": "bhavesh.patel@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 26000,
    "Emergency Contact Name": "Dipti Patel",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541003",
  },
  {
    "Employee Name": "Chirag Verma",
    "Mobile Number": "9876540004",
    "City": "Delhi",
    "Full Address": "C-14, Green Park Extension, New Delhi 110016",
    "Email": "chirag.verma@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 30000,
    "Emergency Contact Name": "Meera Verma",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541004",
  },
  {
    "Employee Name": "Deepak Yadav",
    "Mobile Number": "9876540005",
    "City": "Gurugram",
    "Full Address": "Tower 4, Flat 701, Sector 48, Gurugram 122018",
    "Email": "deepak.yadav@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 850,
    "Emergency Contact Name": "Rakesh Yadav",
    "Emergency Contact Relation": "Sibling",
    "Emergency Contact Number": "9876541005",
  },
  {
    "Employee Name": "Divya Nair",
    "Mobile Number": "9876540006",
    "City": "Kochi",
    "Full Address": "12/450, Marine Drive, Ernakulam, Kochi 682031",
    "Email": "divya.nair@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 25000,
    "Emergency Contact Name": "Suresh Nair",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541006",
  },
  {
    "Employee Name": "Eshwar Rao",
    "Mobile Number": "9876540007",
    "City": "Visakhapatnam",
    "Full Address": "54-12-8, Seethammadhara, Visakhapatnam 530013",
    "Email": "eshwar.rao@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 750,
    "Emergency Contact Name": "Lakshmi Rao",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541007",
  },
  {
    "Employee Name": "Farhan Khan",
    "Mobile Number": "9876540008",
    "City": "Mumbai",
    "Full Address": "Shop 4, Hill Road, Bandra West, Mumbai 400050",
    "Email": "farhan.khan@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 27000,
    "Emergency Contact Name": "Zainab Khan",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541008",
  },
  {
    "Employee Name": "Gautam Mehta",
    "Mobile Number": "9876540009",
    "City": "Pune",
    "Full Address": "Flat 502, Nyati Estate, Mohammadwadi, Pune 411060",
    "Email": "gautam.mehta@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 32000,
    "Emergency Contact Name": "Neha Mehta",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541009",
  },
  {
    "Employee Name": "Geeta Joshi",
    "Mobile Number": "9876540010",
    "City": "Jaipur",
    "Full Address": "88, Malviya Nagar, Jaipur, Rajasthan 302017",
    "Email": "geeta.joshi@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 700,
    "Emergency Contact Name": "Mohan Joshi",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541010",
  },
  {
    "Employee Name": "Harish Iyer",
    "Mobile Number": "9876540011",
    "City": "Chennai",
    "Full Address": "23, 4th Main Road, Gandhi Nagar, Adyar, Chennai 600020",
    "Email": "harish.iyer@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 29000,
    "Emergency Contact Name": "Radha Iyer",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541011",
  },
  {
    "Employee Name": "Himanshu Gupta",
    "Mobile Number": "9876540012",
    "City": "Lucknow",
    "Full Address": "B-20, Gomti Nagar, Lucknow, UP 226010",
    "Email": "himanshu.gupta@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 22000,
    "Emergency Contact Name": "Sunil Gupta",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541012",
  },
  {
    "Employee Name": "Inderpreet Singh",
    "Mobile Number": "9876540013",
    "City": "Chandigarh",
    "Full Address": "House 1542, Sector 35-B, Chandigarh 160022",
    "Email": "inderpreet.singh@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 31000,
    "Emergency Contact Name": "Simran Kaur",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541013",
  },
  {
    "Employee Name": "Ishaan Das",
    "Mobile Number": "9876540014",
    "City": "Kolkata",
    "Full Address": "76/2, Southern Avenue, Lake Gardens, Kolkata 700029",
    "Email": "ishaan.das@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 800,
    "Emergency Contact Name": "Rina Das",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541014",
  },
  {
    "Employee Name": "Jagdish Kulkarni",
    "Mobile Number": "9876540015",
    "City": "Nagpur",
    "Full Address": "Plot 18, Ramdaspeth, Nagpur 440010",
    "Email": "jagdish.k@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 23000,
    "Emergency Contact Name": "Aarti Kulkarni",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541015",
  },
  {
    "Employee Name": "Jyoti Mishra",
    "Mobile Number": "9876540016",
    "City": "Varanasi",
    "Full Address": "D-58/12, Sigra, Varanasi, UP 221010",
    "Email": "jyoti.mishra@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 650,
    "Emergency Contact Name": "Santosh Mishra",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541016",
  },
  {
    "Employee Name": "Karan Malhotra",
    "Mobile Number": "9876540017",
    "City": "Ludhiana",
    "Full Address": "321, Model Town, Ludhiana, Punjab 141002",
    "Email": "karan.malhotra@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 28500,
    "Emergency Contact Name": "Sonia Malhotra",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541017",
  },
  {
    "Employee Name": "Kavita Pillai",
    "Mobile Number": "9876540018",
    "City": "Thiruvananthapuram",
    "Full Address": "TC 14/235, Nandavanam, Thiruvananthapuram 695033",
    "Email": "kavita.pillai@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 26000,
    "Emergency Contact Name": "Girish Pillai",
    "Emergency Contact Relation": "Sibling",
    "Emergency Contact Number": "9876541018",
  },
  {
    "Employee Name": "Lokesh Jain",
    "Mobile Number": "9876540019",
    "City": "Indore",
    "Full Address": "58, Saket Nagar, Indore, MP 452018",
    "Email": "lokesh.jain@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 24500,
    "Emergency Contact Name": "Vimla Jain",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541019",
  },
  {
    "Employee Name": "Madhav Bhatt",
    "Mobile Number": "9876540020",
    "City": "Vadodara",
    "Full Address": "102, Alkapuri Arcade, Vadodara, Gujarat 390007",
    "Email": "madhav.bhatt@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 780,
    "Emergency Contact Name": "Bina Bhatt",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541020",
  },
  {
    "Employee Name": "Manish Tiwari",
    "Mobile Number": "9876540021",
    "City": "Bhopal",
    "Full Address": "E-4, Arera Colony, Bhopal, MP 462016",
    "Email": "manish.tiwari@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 21000,
    "Emergency Contact Name": "Ashok Tiwari",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541021",
  },
  {
    "Employee Name": "Meera Chawla",
    "Mobile Number": "9876540022",
    "City": "Amritsar",
    "Full Address": "45, Mall Road, Amritsar, Punjab 143001",
    "Email": "meera.chawla@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 27500,
    "Emergency Contact Name": "Harpreet Chawla",
    "Emergency Contact Relation": "Sibling",
    "Emergency Contact Number": "9876541022",
  },
  {
    "Employee Name": "Naveen Gowda",
    "Mobile Number": "9876540023",
    "City": "Bengaluru",
    "Full Address": "78, 12th Cross, Indiranagar, Bengaluru 560038",
    "Email": "naveen.gowda@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 35000,
    "Emergency Contact Name": "Shobha Gowda",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541023",
  },
  {
    "Employee Name": "Nisha Agarwal",
    "Mobile Number": "9876540024",
    "City": "Noida",
    "Full Address": "Tower C, Flat 1402, Sector 62, Noida 201309",
    "Email": "nisha.agarwal@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 33000,
    "Emergency Contact Name": "Amit Agarwal",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541024",
  },
  {
    "Employee Name": "Omkar Salunkhe",
    "Mobile Number": "9876540025",
    "City": "Navi Mumbai",
    "Full Address": "Flat 304, Vashi Sector 17, Navi Mumbai 400703",
    "Email": "omkar.salunkhe@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 900,
    "Emergency Contact Name": "Sunanda Salunkhe",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541025",
  },
  {
    "Employee Name": "Pankaj Chauhan",
    "Mobile Number": "9876540026",
    "City": "Dehradun",
    "Full Address": "22, Rajpur Road, Dehradun, Uttarakhand 248001",
    "Email": "pankaj.chauhan@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 23500,
    "Emergency Contact Name": "Virendra Chauhan",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541026",
  },
  {
    "Employee Name": "Parul Saxena",
    "Mobile Number": "9876540027",
    "City": "Kanpur",
    "Full Address": "112/350, Swaroop Nagar, Kanpur, UP 208002",
    "Email": "parul.saxena@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 25000,
    "Emergency Contact Name": "Anand Saxena",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541027",
  },
  {
    "Employee Name": "Pradeep Hegde",
    "Mobile Number": "9876540028",
    "City": "Mangaluru",
    "Full Address": "Kadri Hills, 3rd Block, Mangaluru 575004",
    "Email": "pradeep.hegde@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 720,
    "Emergency Contact Name": "Shubha Hegde",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541028",
  },
  {
    "Employee Name": "Pooja Deshmukh",
    "Mobile Number": "9876540029",
    "City": "Nashik",
    "Full Address": "15, Gangapur Road, Nashik 422013",
    "Email": "pooja.deshmukh@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 26500,
    "Emergency Contact Name": "Sanjay Deshmukh",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541029",
  },
  {
    "Employee Name": "Rahul Bose",
    "Mobile Number": "9876540030",
    "City": "Kolkata",
    "Full Address": "Flat 4A, Salt Lake Sector 2, Kolkata 700091",
    "Email": "rahul.bose@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 31000,
    "Emergency Contact Name": "Maitreyi Bose",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541030",
  },
  {
    "Employee Name": "Rakesh Nambiar",
    "Mobile Number": "9876540031",
    "City": "Kozhikode",
    "Full Address": "Beach Road, Near Gandhi Park, Kozhikode 673032",
    "Email": "rakesh.nambiar@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 820,
    "Emergency Contact Name": "Sujatha Nambiar",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541031",
  },
  {
    "Employee Name": "Rashmi Dubey",
    "Mobile Number": "9876540032",
    "City": "Jabalpur",
    "Full Address": "Wright Town, Gate No 3, Jabalpur, MP 482002",
    "Email": "rashmi.dubey@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 20500,
    "Emergency Contact Name": "Vinod Dubey",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541032",
  },
  {
    "Employee Name": "Rohan Sen",
    "Mobile Number": "9876540033",
    "City": "Howrah",
    "Full Address": "42, Grand Trunk Road, Howrah, WB 711101",
    "Email": "rohan.sen@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 24000,
    "Emergency Contact Name": "Debasree Sen",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541033",
  },
  {
    "Employee Name": "Sachin Tendulkar",
    "Mobile Number": "9876540034",
    "City": "Thane",
    "Full Address": "Pokhran Road No 2, Thane West 400610",
    "Email": "sachin.t@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 29500,
    "Emergency Contact Name": "Anjali Tendulkar",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541034",
  },
  {
    "Employee Name": "Sameer Sheikh",
    "Mobile Number": "9876540035",
    "City": "Aurangabad",
    "Full Address": "Samarth Nagar, CIDCO, Aurangabad 431001",
    "Email": "sameer.sheikh@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 760,
    "Emergency Contact Name": "Farida Sheikh",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541035",
  },
  {
    "Employee Name": "Sandhya Murthy",
    "Mobile Number": "9876540036",
    "City": "Mysuru",
    "Full Address": "14, Saraswathipuram, Mysuru, Karnataka 570009",
    "Email": "sandhya.murthy@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 25000,
    "Emergency Contact Name": "Narayana Murthy",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541036",
  },
  {
    "Employee Name": "Santosh Mahapatra",
    "Mobile Number": "9876540037",
    "City": "Bhubaneswar",
    "Full Address": "Plot 240, Saheed Nagar, Bhubaneswar 751007",
    "Email": "santosh.m@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 22500,
    "Emergency Contact Name": "Prativa Mahapatra",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541037",
  },
  {
    "Employee Name": "Sarita Mondal",
    "Mobile Number": "9876540038",
    "City": "Siliguri",
    "Full Address": "Sevoke Road, 2nd Mile, Siliguri, WB 734001",
    "Email": "sarita.mondal@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 680,
    "Emergency Contact Name": "Subhash Mondal",
    "Emergency Contact Relation": "Sibling",
    "Emergency Contact Number": "9876541038",
  },
  {
    "Employee Name": "Shashank Shukla",
    "Mobile Number": "9876540039",
    "City": "Prayagraj",
    "Full Address": "5, Civil Lines, Prayagraj, UP 211001",
    "Email": "shashank.shukla@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 24000,
    "Emergency Contact Name": "Ram Shukla",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541039",
  },
  {
    "Employee Name": "Sneha Kulkarni",
    "Mobile Number": "9876540040",
    "City": "Solapur",
    "Full Address": "77, Railway Lines, Solapur, Maharashtra 413001",
    "Email": "sneha.kulkarni@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 23000,
    "Emergency Contact Name": "Vijay Kulkarni",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541040",
  },
  {
    "Employee Name": "Subhash Chandra",
    "Mobile Number": "9876540041",
    "City": "Ranchi",
    "Full Address": "Circular Road, Lalpur, Ranchi, Jharkhand 834001",
    "Email": "subhash.c@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 700,
    "Emergency Contact Name": "Kamla Chandra",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541041",
  },
  {
    "Employee Name": "Sudhir Patnaik",
    "Mobile Number": "9876540042",
    "City": "Cuttack",
    "Full Address": "Badambadi Colony, Cuttack, Odisha 753012",
    "Email": "sudhir.patnaik@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 21500,
    "Emergency Contact Name": "Minati Patnaik",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541042",
  },
  {
    "Employee Name": "Tanmay Ghosh",
    "Mobile Number": "9876540043",
    "City": "Durgapur",
    "Full Address": "City Centre, Sector 2, Durgapur, WB 713216",
    "Email": "tanmay.ghosh@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 25500,
    "Emergency Contact Name": "Alok Ghosh",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541043",
  },
  {
    "Employee Name": "Tarun Kapoor",
    "Mobile Number": "9876540044",
    "City": "Faridabad",
    "Full Address": "Sector 15, Faridabad, Haryana 121007",
    "Email": "tarun.kapoor@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 27000,
    "Emergency Contact Name": "Richa Kapoor",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541044",
  },
  {
    "Employee Name": "Umesh Rawat",
    "Mobile Number": "9876540045",
    "City": "Haridwar",
    "Full Address": "Ranipur More, Haridwar, Uttarakhand 249401",
    "Email": "umesh.rawat@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 740,
    "Emergency Contact Name": "Sarita Rawat",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541045",
  },
  {
    "Employee Name": "Vaishali Deshmukh",
    "Mobile Number": "9876540046",
    "City": "Kolhapur",
    "Full Address": "Shahupuri 3rd Lane, Kolhapur 416001",
    "Email": "vaishali.d@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 24000,
    "Emergency Contact Name": "Pradeep Deshmukh",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541046",
  },
  {
    "Employee Name": "Vikas Choudhary",
    "Mobile Number": "9876540047",
    "City": "Jodhpur",
    "Full Address": "Shastri Nagar, Sector E, Jodhpur, Rajasthan 342003",
    "Email": "vikas.c@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 26000,
    "Emergency Contact Name": "Santosh Choudhary",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541047",
  },
  {
    "Employee Name": "Vinay Kulkarni",
    "Mobile Number": "9876540048",
    "City": "Belagavi",
    "Full Address": "Tilakwadi, 2nd Railway Gate, Belagavi 590006",
    "Email": "vinay.kulkarni@retailnext.in",
    "Salary Type": "Daily",
    "Salary Amount (INR)": 800,
    "Emergency Contact Name": "Savita Kulkarni",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541048",
  },
  {
    "Employee Name": "Yashwant Sinha",
    "Mobile Number": "9876540049",
    "City": "Patna",
    "Full Address": "Kankarbagh Colony, Patna, Bihar 800020",
    "Email": "yashwant.sinha@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 25000,
    "Emergency Contact Name": "Gopal Sinha",
    "Emergency Contact Relation": "Parent",
    "Emergency Contact Number": "9876541049",
  },
  {
    "Employee Name": "Zeeshan Ali",
    "Mobile Number": "9876540050",
    "City": "Hyderabad",
    "Full Address": "Near Charminar, Moghalpura, Hyderabad 500002",
    "Email": "zeeshan.ali@retailnext.in",
    "Salary Type": "Monthly",
    "Salary Amount (INR)": 28000,
    "Emergency Contact Name": "Shabana Ali",
    "Emergency Contact Relation": "Spouse",
    "Emergency Contact Number": "9876541050",
  },
];
