export interface SampleClothingProductItem {
  "Product Name": string;
  "Category": string;
  "Sub Category": string;
  "Price": number;
  "Discount Available": string;
  "Discount Type": string;
  "Discount Value": number;
  "Buffer Stock": number;
  "Description": string;
  "Barcode": string;
  "Image URL": string;
  "Variation 1 (Color)"?: string;
  "Variation 2 (Size)"?: string;
}

export const SAMPLE_CLOTHING_PRODUCTS: SampleClothingProductItem[] = [
  // 1. MEN'S WEAR -> T-SHIRTS (Multi-level: Color + Size)
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 5, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Jet Black", "Variation 2 (Size)": "S" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 6, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Jet Black", "Variation 2 (Size)": "M" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 8, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Jet Black", "Variation 2 (Size)": "L" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 549, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 5, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Jet Black", "Variation 2 (Size)": "XL" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 549, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Jet Black", "Variation 2 (Size)": "XXL" },

  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 5, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Navy Blue", "Variation 2 (Size)": "S" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 6, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Navy Blue", "Variation 2 (Size)": "M" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 8, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Navy Blue", "Variation 2 (Size)": "L" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 549, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 5, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Navy Blue", "Variation 2 (Size)": "XL" },

  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 4, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Olive Green", "Variation 2 (Size)": "M" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 499, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 6, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Olive Green", "Variation 2 (Size)": "L" },
  { "Product Name": "Premium Combed Cotton Crew Neck T-Shirt", "Category": "Men's Wear", "Sub Category": "T-Shirts", "Price": 549, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 4, "Description": "180 GSM bio-washed pre-shrunk daily wear t-shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Olive Green", "Variation 2 (Size)": "XL" },

  // 2. MEN'S WEAR -> POLO SHIRTS (Color + Size)
  { "Product Name": "Solid Classic Pique Polo T-Shirt", "Category": "Men's Wear", "Sub Category": "Polo T-Shirts", "Price": 799, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Pure cotton honeycomb pique knit polo shirt with ribbed cuffs", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Crimson Red", "Variation 2 (Size)": "M" },
  { "Product Name": "Solid Classic Pique Polo T-Shirt", "Category": "Men's Wear", "Sub Category": "Polo T-Shirts", "Price": 799, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 5, "Description": "Pure cotton honeycomb pique knit polo shirt with ribbed cuffs", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Crimson Red", "Variation 2 (Size)": "L" },
  { "Product Name": "Solid Classic Pique Polo T-Shirt", "Category": "Men's Wear", "Sub Category": "Polo T-Shirts", "Price": 849, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 3, "Description": "Pure cotton honeycomb pique knit polo shirt with ribbed cuffs", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Crimson Red", "Variation 2 (Size)": "XL" },

  { "Product Name": "Solid Classic Pique Polo T-Shirt", "Category": "Men's Wear", "Sub Category": "Polo T-Shirts", "Price": 799, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 5, "Description": "Pure cotton honeycomb pique knit polo shirt with ribbed cuffs", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Royal Blue", "Variation 2 (Size)": "M" },
  { "Product Name": "Solid Classic Pique Polo T-Shirt", "Category": "Men's Wear", "Sub Category": "Polo T-Shirts", "Price": 799, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 6, "Description": "Pure cotton honeycomb pique knit polo shirt with ribbed cuffs", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Royal Blue", "Variation 2 (Size)": "L" },
  { "Product Name": "Solid Classic Pique Polo T-Shirt", "Category": "Men's Wear", "Sub Category": "Polo T-Shirts", "Price": 849, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 4, "Description": "Pure cotton honeycomb pique knit polo shirt with ribbed cuffs", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Royal Blue", "Variation 2 (Size)": "XL" },

  // 3. MEN'S WEAR -> FORMAL SHIRTS (Color + Size)
  { "Product Name": "Executive Oxford Cotton Dress Shirt", "Category": "Men's Wear", "Sub Category": "Formal Shirts", "Price": 1299, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Wrinkle-free pin-point Oxford weave tailored formal dress shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pure White", "Variation 2 (Size)": "39 (M)" },
  { "Product Name": "Executive Oxford Cotton Dress Shirt", "Category": "Men's Wear", "Sub Category": "Formal Shirts", "Price": 1299, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 5, "Description": "Wrinkle-free pin-point Oxford weave tailored formal dress shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pure White", "Variation 2 (Size)": "40 (M)" },
  { "Product Name": "Executive Oxford Cotton Dress Shirt", "Category": "Men's Wear", "Sub Category": "Formal Shirts", "Price": 1299, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 6, "Description": "Wrinkle-free pin-point Oxford weave tailored formal dress shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pure White", "Variation 2 (Size)": "42 (L)" },
  { "Product Name": "Executive Oxford Cotton Dress Shirt", "Category": "Men's Wear", "Sub Category": "Formal Shirts", "Price": 1399, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 4, "Description": "Wrinkle-free pin-point Oxford weave tailored formal dress shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pure White", "Variation 2 (Size)": "44 (XL)" },

  { "Product Name": "Executive Oxford Cotton Dress Shirt", "Category": "Men's Wear", "Sub Category": "Formal Shirts", "Price": 1299, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Wrinkle-free pin-point Oxford weave tailored formal dress shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Sky Blue", "Variation 2 (Size)": "40 (M)" },
  { "Product Name": "Executive Oxford Cotton Dress Shirt", "Category": "Men's Wear", "Sub Category": "Formal Shirts", "Price": 1299, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 5, "Description": "Wrinkle-free pin-point Oxford weave tailored formal dress shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Sky Blue", "Variation 2 (Size)": "42 (L)" },
  { "Product Name": "Executive Oxford Cotton Dress Shirt", "Category": "Men's Wear", "Sub Category": "Formal Shirts", "Price": 1399, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 3, "Description": "Wrinkle-free pin-point Oxford weave tailored formal dress shirt", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Sky Blue", "Variation 2 (Size)": "44 (XL)" },

  // 4. MEN'S WEAR -> DENIM & JEANS (Color + Waist Size)
  { "Product Name": "Men's Stretch Slim Fit Denim Jeans", "Category": "Men's Wear", "Sub Category": "Jeans", "Price": 1699, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 4, "Description": "Mid-rise stretch 12oz denim with whiskers and contrast stitch", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Dark Indigo", "Variation 2 (Size)": "30" },
  { "Product Name": "Men's Stretch Slim Fit Denim Jeans", "Category": "Men's Wear", "Sub Category": "Jeans", "Price": 1699, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 6, "Description": "Mid-rise stretch 12oz denim with whiskers and contrast stitch", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Dark Indigo", "Variation 2 (Size)": "32" },
  { "Product Name": "Men's Stretch Slim Fit Denim Jeans", "Category": "Men's Wear", "Sub Category": "Jeans", "Price": 1699, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 6, "Description": "Mid-rise stretch 12oz denim with whiskers and contrast stitch", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Dark Indigo", "Variation 2 (Size)": "34" },
  { "Product Name": "Men's Stretch Slim Fit Denim Jeans", "Category": "Men's Wear", "Sub Category": "Jeans", "Price": 1799, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 5, "Description": "Mid-rise stretch 12oz denim with whiskers and contrast stitch", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Dark Indigo", "Variation 2 (Size)": "36" },

  { "Product Name": "Men's Stretch Slim Fit Denim Jeans", "Category": "Men's Wear", "Sub Category": "Jeans", "Price": 1699, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 3, "Description": "Mid-rise stretch 12oz denim with whiskers and contrast stitch", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Faded Charcoal", "Variation 2 (Size)": "32" },
  { "Product Name": "Men's Stretch Slim Fit Denim Jeans", "Category": "Men's Wear", "Sub Category": "Jeans", "Price": 1699, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 5, "Description": "Mid-rise stretch 12oz denim with whiskers and contrast stitch", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Faded Charcoal", "Variation 2 (Size)": "34" },
  { "Product Name": "Men's Stretch Slim Fit Denim Jeans", "Category": "Men's Wear", "Sub Category": "Jeans", "Price": 1799, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 4, "Description": "Mid-rise stretch 12oz denim with whiskers and contrast stitch", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Faded Charcoal", "Variation 2 (Size)": "36" },

  // 5. WOMEN'S WEAR -> ETHNIC KURTIS (Color + Size)
  { "Product Name": "Jaipuri Handblock Pure Cotton Anarkali Kurti", "Category": "Women's Wear", "Sub Category": "Ethnic Kurtis", "Price": 1099, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Flowy flared flared floral printed cotton kurti with potli buttons", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Mustard Yellow", "Variation 2 (Size)": "S" },
  { "Product Name": "Jaipuri Handblock Pure Cotton Anarkali Kurti", "Category": "Women's Wear", "Sub Category": "Ethnic Kurtis", "Price": 1099, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 5, "Description": "Flowy flared flared floral printed cotton kurti with potli buttons", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Mustard Yellow", "Variation 2 (Size)": "M" },
  { "Product Name": "Jaipuri Handblock Pure Cotton Anarkali Kurti", "Category": "Women's Wear", "Sub Category": "Ethnic Kurtis", "Price": 1099, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 6, "Description": "Flowy flared flared floral printed cotton kurti with potli buttons", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Mustard Yellow", "Variation 2 (Size)": "L" },
  { "Product Name": "Jaipuri Handblock Pure Cotton Anarkali Kurti", "Category": "Women's Wear", "Sub Category": "Ethnic Kurtis", "Price": 1199, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 4, "Description": "Flowy flared flared floral printed cotton kurti with potli buttons", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Mustard Yellow", "Variation 2 (Size)": "XL" },

  { "Product Name": "Jaipuri Handblock Pure Cotton Anarkali Kurti", "Category": "Women's Wear", "Sub Category": "Ethnic Kurtis", "Price": 1099, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 3, "Description": "Flowy flared flared floral printed cotton kurti with potli buttons", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Indigo Blue", "Variation 2 (Size)": "M" },
  { "Product Name": "Jaipuri Handblock Pure Cotton Anarkali Kurti", "Category": "Women's Wear", "Sub Category": "Ethnic Kurtis", "Price": 1099, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 5, "Description": "Flowy flared flared floral printed cotton kurti with potli buttons", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Indigo Blue", "Variation 2 (Size)": "L" },
  { "Product Name": "Jaipuri Handblock Pure Cotton Anarkali Kurti", "Category": "Women's Wear", "Sub Category": "Ethnic Kurtis", "Price": 1199, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 3, "Description": "Flowy flared flared floral printed cotton kurti with potli buttons", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Indigo Blue", "Variation 2 (Size)": "XL" },

  // 6. WOMEN'S WEAR -> WESTERN DRESSES (Color + Size)
  { "Product Name": "Tiered Floral Georgette Midi Dress", "Category": "Women's Wear", "Sub Category": "Dresses", "Price": 1499, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 3, "Description": "Breezy tiered georgette dress with smocked bodice and lining", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pastel Peach", "Variation 2 (Size)": "XS" },
  { "Product Name": "Tiered Floral Georgette Midi Dress", "Category": "Women's Wear", "Sub Category": "Dresses", "Price": 1499, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Breezy tiered georgette dress with smocked bodice and lining", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pastel Peach", "Variation 2 (Size)": "S" },
  { "Product Name": "Tiered Floral Georgette Midi Dress", "Category": "Women's Wear", "Sub Category": "Dresses", "Price": 1499, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 5, "Description": "Breezy tiered georgette dress with smocked bodice and lining", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pastel Peach", "Variation 2 (Size)": "M" },
  { "Product Name": "Tiered Floral Georgette Midi Dress", "Category": "Women's Wear", "Sub Category": "Dresses", "Price": 1599, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Breezy tiered georgette dress with smocked bodice and lining", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Pastel Peach", "Variation 2 (Size)": "L" },

  // 7. KIDS WEAR -> BOYS APPAREL (Size/Age)
  { "Product Name": "Boys Cotton Dinosaur Graphic T-Shirt", "Category": "Kids Wear", "Sub Category": "Boys Apparel", "Price": 399, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 4, "Description": "Soft combed pure cotton playful graphic print t-shirt for kids", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Bright Yellow", "Variation 2 (Size)": "3-4 Years" },
  { "Product Name": "Boys Cotton Dinosaur Graphic T-Shirt", "Category": "Kids Wear", "Sub Category": "Boys Apparel", "Price": 399, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 5, "Description": "Soft combed pure cotton playful graphic print t-shirt for kids", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Bright Yellow", "Variation 2 (Size)": "5-6 Years" },
  { "Product Name": "Boys Cotton Dinosaur Graphic T-Shirt", "Category": "Kids Wear", "Sub Category": "Boys Apparel", "Price": 429, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 6, "Description": "Soft combed pure cotton playful graphic print t-shirt for kids", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Bright Yellow", "Variation 2 (Size)": "7-8 Years" },

  // 8. KIDS WEAR -> GIRLS DRESSES (Size/Age)
  { "Product Name": "Girls Floral Ruffled Party Frock", "Category": "Kids Wear", "Sub Category": "Girls Dresses", "Price": 799, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Cotton lined party frock with back bow tie and flutter sleeves", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Blush Pink", "Variation 2 (Size)": "3-4 Years" },
  { "Product Name": "Girls Floral Ruffled Party Frock", "Category": "Kids Wear", "Sub Category": "Girls Dresses", "Price": 799, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 5, "Description": "Cotton lined party frock with back bow tie and flutter sleeves", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Blush Pink", "Variation 2 (Size)": "5-6 Years" },
  { "Product Name": "Girls Floral Ruffled Party Frock", "Category": "Kids Wear", "Sub Category": "Girls Dresses", "Price": 849, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 4, "Description": "Cotton lined party frock with back bow tie and flutter sleeves", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Blush Pink", "Variation 2 (Size)": "7-8 Years" },

  // 9. WINTER WEAR -> HOODIES & JACKETS (Color + Size)
  { "Product Name": "Heavyweight Fleece Kangaroo Pocket Hoodie", "Category": "Winter Wear", "Sub Category": "Hoodies", "Price": 1499, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 3, "Description": "380 GSM warm brushed cotton fleece pullover with double hood", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Heather Grey", "Variation 2 (Size)": "M" },
  { "Product Name": "Heavyweight Fleece Kangaroo Pocket Hoodie", "Category": "Winter Wear", "Sub Category": "Hoodies", "Price": 1499, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 5, "Description": "380 GSM warm brushed cotton fleece pullover with double hood", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Heather Grey", "Variation 2 (Size)": "L" },
  { "Product Name": "Heavyweight Fleece Kangaroo Pocket Hoodie", "Category": "Winter Wear", "Sub Category": "Hoodies", "Price": 1599, "Discount Available": "Yes", "Discount Type": "Rupees", "Discount Value": 100, "Buffer Stock": 4, "Description": "380 GSM warm brushed cotton fleece pullover with double hood", "Barcode": "", "Image URL": "", "Variation 1 (Color)": "Heather Grey", "Variation 2 (Size)": "XL" },

  // 10. ACCESSORIES -> BELTS & CAPS (Simple Items)
  { "Product Name": "Full-Grain Leather Reversible Formal Belt", "Category": "Accessories", "Sub Category": "Belts", "Price": 799, "Discount Available": "No", "Discount Type": "", "Discount Value": 0, "Buffer Stock": 8, "Description": "Genuine Italian leather double-sided Black & Brown dress belt", "Barcode": "", "Image URL": "" },
  { "Product Name": "Cotton Twill Adjustable Classic Baseball Cap", "Category": "Accessories", "Sub Category": "Caps", "Price": 399, "Discount Available": "Yes", "Discount Type": "Percentage", "Discount Value": 15, "Buffer Stock": 10, "Description": "6-panel breathable washed cotton cap with metal slider strap", "Barcode": "", "Image URL": "" },
];
